"""initial schema

Revision ID: 1100434363a6
Revises: 
Create Date: 2026-08-30 22:59:05.669838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1100434363a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_task',
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('journal_name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('journal', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('issue', sa.String(length=20), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('literature_type', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('video_note_task',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('bvid', sa.String(length=64), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('whisper_model', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('device', sa.String(length=32), nullable=False),
    sa.Column('compute_type', sa.String(length=32), nullable=False),
    sa.Column('use_vad', sa.Boolean(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('note_path', sa.Text(), nullable=True),
    sa.Column('metadata_path', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_note_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_note_task_bvid'), ['bvid'], unique=False)

    op.create_table('crawl_task_log',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_task_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_task_log_task_id'), ['task_id'], unique=False)

    op.create_table('literature_folder',
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('literature_id', 'folder_id')
    )
    op.create_table('literature_tag',
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('literature_id', 'tag_id')
    )
    op.create_table('note',
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('position_info', sa.String(length=200), nullable=True),
    sa.Column('excerpt_type', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_issue',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('journal_name', sa.String(length=255), nullable=False),
    sa.Column('journal_slug', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('translation_status', sa.String(length=32), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('raw_json_path', sa.String(length=500), nullable=True),
    sa.Column('crawl_task_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_task_id'], ['crawl_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'journal_name', 'year', 'issue', name='uq_raw_issue_identity')
    )
    with op.batch_alter_table('raw_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_issue_crawl_task_id'), ['crawl_task_id'], unique=False)

    op.create_table('video_note_task_log',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['video_note_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_note_task_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_note_task_log_task_id'), ['task_id'], unique=False)

    op.create_table('raw_issue_analysis',
    sa.Column('raw_issue_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('artifact_md_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_issue_id'], ['raw_issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_issue_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_issue_analysis_raw_issue_id'), ['raw_issue_id'], unique=False)

    op.create_table('raw_paper',
    sa.Column('raw_issue_id', sa.Integer(), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_zh', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_zh', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('pages', sa.String(length=100), nullable=True),
    sa.Column('detail_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('translation_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_issue_id'], ['raw_issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_paper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_paper_raw_issue_id'), ['raw_issue_id'], unique=False)

    op.create_table('llm_run',
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('raw_paper_id', sa.Integer(), nullable=True),
    sa.Column('raw_issue_analysis_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_issue_analysis_id'], ['raw_issue_analysis.id'], ),
    sa.ForeignKeyConstraint(['raw_paper_id'], ['raw_paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_run_raw_issue_analysis_id'), ['raw_issue_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_run_raw_paper_id'), ['raw_paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_run_raw_paper_id'))
        batch_op.drop_index(batch_op.f('ix_llm_run_raw_issue_analysis_id'))

    op.drop_table('llm_run')
    with op.batch_alter_table('raw_paper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_paper_raw_issue_id'))

    op.drop_table('raw_paper')
    with op.batch_alter_table('raw_issue_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_issue_analysis_raw_issue_id'))

    op.drop_table('raw_issue_analysis')
    with op.batch_alter_table('video_note_task_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_note_task_log_task_id'))

    op.drop_table('video_note_task_log')
    with op.batch_alter_table('raw_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_issue_crawl_task_id'))

    op.drop_table('raw_issue')
    op.drop_table('note')
    op.drop_table('literature_tag')
    op.drop_table('literature_folder')
    with op.batch_alter_table('crawl_task_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_task_log_task_id'))

    op.drop_table('crawl_task_log')
    with op.batch_alter_table('video_note_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_note_task_bvid'))

    op.drop_table('video_note_task')
    op.drop_table('tag')
    op.drop_table('literature')
    op.drop_table('folder')
    op.drop_table('crawl_task')
    # ### end Alembic commands ###
