"""add llm profiles and paper analyses

Revision ID: 5703b05951aa
Revises: e84f3c9a61b2
Create Date: 2026-09-07 21:07:31.432809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5703b05951aa'
down_revision = 'e84f3c9a61b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_check_status', sa.String(length=20), nullable=True),
    sa.Column('last_check_message', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_profile')),
    sa.UniqueConstraint('name', name=op.f('uq_llm_profile_name'))
    )
    op.create_table('llm_scene_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['llm_profile.id'], name=op.f('fk_llm_scene_binding_profile_id_llm_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_scene_binding')),
    sa.UniqueConstraint('scene', name=op.f('uq_llm_scene_binding_scene'))
    )
    profile_table = sa.table(
        'llm_profile',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('protocol', sa.String),
        sa.column('base_url', sa.String),
        sa.column('model_name', sa.String),
        sa.column('enabled', sa.Boolean),
    )
    op.bulk_insert(
        profile_table,
        [
            {
                'id': 1,
                'name': 'Gemini 论文工作',
                'protocol': 'gemini',
                'base_url': None,
                'model_name': 'gemini-3-flash-preview',
                'enabled': True,
            },
            {
                'id': 2,
                'name': 'Gemini 视频笔记',
                'protocol': 'gemini',
                'base_url': None,
                'model_name': 'gemini-2.5-flash',
                'enabled': True,
            },
        ],
    )
    binding_table = sa.table(
        'llm_scene_binding',
        sa.column('scene', sa.String),
        sa.column('profile_id', sa.Integer),
    )
    op.bulk_insert(
        binding_table,
        [
            {'scene': 'paper_analysis', 'profile_id': 1},
            {'scene': 'paper_translation', 'profile_id': 1},
            {'scene': 'video_note', 'profile_id': 2},
        ],
    )
    op.create_table('paper_analysis',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('artifact_md_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['llm_profile.id'], name=op.f('fk_paper_analysis_profile_id_llm_profile'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_analysis'))
    )
    op.create_table('paper_analysis_item',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('literature_id', sa.Integer(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('issue', sa.String(length=20), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['paper_analysis.id'], name=op.f('fk_paper_analysis_item_analysis_id_paper_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], name=op.f('fk_paper_analysis_item_literature_id_literature'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_analysis_item')),
    sa.UniqueConstraint('analysis_id', 'literature_id', name='uq_analysis_literature')
    )
    with op.batch_alter_table('paper_analysis_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_analysis_item_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_analysis_item_literature_id'), ['literature_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_analysis_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_analysis_item_literature_id'))
        batch_op.drop_index(batch_op.f('ix_paper_analysis_item_analysis_id'))

    op.drop_table('paper_analysis_item')
    op.drop_table('paper_analysis')
    op.drop_table('llm_scene_binding')
    op.drop_table('llm_profile')
    # ### end Alembic commands ###
