"""add journal and paper provenance

Revision ID: c9b826cfa1c0
Revises: 1100434363a6
Create Date: 2026-08-31 16:00:51.685153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b826cfa1c0'
down_revision = '1100434363a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal')),
    sa.UniqueConstraint('name', name=op.f('uq_journal_name'))
    )
    op.create_table('journal_source_config',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name=op.f('fk_journal_source_config_journal_id_journal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_source_config')),
    sa.UniqueConstraint('journal_id', 'source_id', name='uq_journal_source')
    )
    with op.batch_alter_table('journal_source_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_source_config_journal_id'), ['journal_id'], unique=False)

    with op.batch_alter_table('literature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='imported', nullable=False))
        batch_op.add_column(sa.Column('source_raw_paper_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_literature_journal_id_journal'), 'journal', ['journal_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('literature', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_literature_journal_id_journal'), type_='foreignkey')
        batch_op.drop_column('journal_id')
        batch_op.drop_column('source_raw_paper_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('journal_source_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_source_config_journal_id'))

    op.drop_table('journal_source_config')
    op.drop_table('journal')
    # ### end Alembic commands ###
